### ISSUE TITLE
ios12.2无法运行

### ISSUE THREAD

**Issue by silence1996** [shrekshrek/orienter#3]
您好，这个库好像在ios上无法运行，我的ios版本是12.2。此前有用过您这个库，当时ios11是可以用的，是ios12的问题吗。

**Comment by vito24** [comment]
@silence1996 请问你的问题解决了吗？

**Comment by vito24** [comment]
知道问题了，iOS12.2之后，默认关闭了陀螺仪，需要在设置里手动打开
